apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-learning-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-learning
  template:
    metadata:
      labels:
        app: e-learning
    spec:
      containers:
        - name: e-learning-container
          image: e-learning-site:latest
          imagePullPolicy: Never   # 👈 prevents Kubernetes from pulling from Docker Hub
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: e-learning-service
spec:
  selector:
    app: e-learning
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
